name: CI/CD - LocalStack Terraform Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  terraform-localstack:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
        options: >-
          --health-cmd "curl -s http://localhost:4566/health | grep '\"s3\": \"running\"'"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Terraform Outputs
        working-directory: ./terraform
        run: terraform output

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
