name: Full DevOps Automation - Docker + Terraform + LocalStack

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  full-pipeline:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
          LS_LOG: trace
        options: >-
          --entrypoint ""

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Wait until LocalStack is ready (custom retry)
      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          for i in {1..60}; do
            if curl -s http://localhost:4566/health | grep '"s3": "running"' > /dev/null; then
              echo "✅ LocalStack is ready!"
              exit 0
            fi
            echo "Still waiting... ($i)"
            sleep 5
          done
          echo "❌ LocalStack failed to start in time."
          docker logs $(docker ps -aqf "ancestor=localstack/localstack")
          exit 1

      # Terraform setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8_
