@'
name: Full DevOps Automation - Docker + Terraform + LocalStack

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  full-pipeline:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
        options: >-
          --health-cmd "curl -s http://localhost:4566/_localstack/health | grep 'running' || exit 1"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🕓 Wait until LocalStack is ready
      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:4566/_localstack/health | grep '"s3": "running"' > /dev/null; then
              echo "✅ LocalStack is ready!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 5
          done

      # Terraform setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Terraform Outputs
        working-directory: ./terraform
        run: terraform output

      # Docker build and test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Flask App
        run: docker build -t flask-app .

      - name: Run Flask App
        run: docker run -d -p 5000:5000 --name flask-app flask-app

      - name: Wait for Flask App
        run: sleep 5

      - name: Test Flask App
        run: curl -f http://localhost:5000

      # Clean up
      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
'@ | Set-Content "$env:USERPROFILE\Desktop\8byte-devops-assignment\.github\workflows\ci-cd.yml"
