name: Full DevOps Automation - Docker + Terraform + LocalStack

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  full-pipeline:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
          LS_LOG: trace
        options: >-
          --health-cmd "curl -s http://localhost:4566/_localstack/health | grep 'running' || exit 1"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for LocalStack readiness
        run: |
          echo "Waiting for LocalStack to be ready..."
          for i in {1..60}; do
            HEALTH=$(curl -s http://localhost:4566/_localstack/health || true)
            echo "$HEALTH"
            if echo "$HEALTH" | grep -q '"s3": "running"'; then
              echo "✅ LocalStack is ready!"
              exit 0
            fi
            echo "⏳ Still waiting... ($i/60)"
            sleep 10
          done
          echo "❌ LocalStack failed to start."
          docker ps -a
          docker logs $(docker ps -aqf "ancestor=localstack/localstack")
          exit 1

      # Terraform setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade

      - name: Terraform Apply (with retry)
        working-directory: ./terraform
        run: |
          for i in {1..3}; do
            terraform apply -auto-approve && break || {
              echo "Terraform failed on attempt $i, retrying in 15s..."
              sleep 15
            }
            if [ $i -eq 3 ]; then
              echo "❌ Terraform failed after 3 retries"
              exit 1
            fi
          done

      - name: Terraform Outputs
        working-directory: ./terraform
        run: terraform output

      # ✅ Verify the bucket exists in LocalStack
      - name: Verify S3 Bucket in LocalStack
        run: |
          echo "Listing S3 buckets in LocalStack..."
          awslocal s3 ls || (echo "❌ Failed to list buckets" && exit 1)

      # Docker build and test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Flask App
        run: docker build -t flask-app .

      - name: Run Flask App
        run: docker run -d -p 5000:5000 --name flask-app flask-app

      - name: Wait for Flask App
        run: sleep 5

      - name: Test Flask App
        run: |
          echo "Testing Flask app..."
          curl -f http://localhost:5000 || (echo "Flask app failed!" && exit 1)

      # Terraform cleanup
      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
