name: Full DevOps Automation - Terraform + Docker + LocalStack

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  full-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start LocalStack container
        run: |
          echo "🚀 Starting LocalStack..."
          docker run -d --name localstack \
            -p 4566:4566 \
            -e SERVICES=s3 \
            -e DEBUG=1 \
            -e LS_LOG=trace \
            localstack/localstack:latest
          echo "Waiting for LocalStack to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:4566/_localstack/health | grep '"s3": "running"' > /dev/null; then
              echo "✅ LocalStack is ready!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 5
          done
          docker ps

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Terraform Outputs
        working-directory: ./terraform
        run: terraform output

      - name: Verify S3 bucket
        run: |
          echo "Verifying S3 bucket in LocalStack..."
          docker exec localstack awslocal s3 ls

      - name: Build Flask app
        run: docker build -t flask-app .

      - name: Run Flask app
        run: docker run -d -p 5000:5000 --name flask-app flask-app

      - name: Wait for Flask app
        run: sleep 5

      - name: Test Flask app
        run: curl -f http://localhost:5000

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve

      - name: Cleanup containers
        if: always()
        run: |
          docker stop flask-app localstack || true
          docker rm flask-app localstack || true
